### ISSUE TITLE
Switch Three.js and GLTFLoader to ES Modules

### ISSUE THREAD

**Issue by Luntay01** [Luntay01/ft_transcendence#5]
### Description:
Currently, Three.js and GLTFLoader are included globally in the HTML file (`<script>` tags). While this works, switching to ES modules would:
- Ensure Three.js and GLTFLoader are loaded only when needed.
- Improve modularity and maintainability of the codebase.
- Align with modern JavaScript practices.

### Related Commit:
[20dd266](https://github.com/Luntay01/ft_transcendence/commit/20dd266b2350351f0d884076056ffaad6258578d) - Including Three.js and GLTFLoader directly in the HTML file.

### Tasks:
- [ ] Replace global `<script>` tags with ES module imports for Three.js and GLTFLoader.
- [ ] Update all affected files to use ES imports.
- [ ] Test functionality to ensure the transition doesn’t break the application.

### Priority:
Low - No immediate issues, but a worthwhile improvement for code quality.

**Comment by W41T3D3V1L** [comment]
Remove Global Script Tags:
step 1
Locate the `<script>` tags for Three.js and GLTFLoader in your HTML file and remove them.

Step 2
Use ES Module Imports in Your JavaScript File:
Import Three.js and GLTFLoader using ES modules in your main JavaScript file.
example:
`import * as THREE from 'https://unpkg.com/three@latest/build/three.module.js';
import { GLTFLoader } from 'https://unpkg.com/three@latest/examples/jsm/loaders/GLTFLoader.js';

const scene = new THREE.Scene();
const loader = new GLTFLoader();
`
step 3 
Ensure Your Script Uses type="module" in HTML:
Update the script reference in your HTML file:
`<script type="module" src="main.js"></script>`

step 4
Check Compatibility & Fix Relative Imports (If Needed):
`npm install three
`
mport modules locally:
'import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';`

done
Run your project and check the browser console for any errors.
